import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ProvidersComponent from '@/components/ProviderComponent'
import NavbarComponent from '@/components/NavBarComponent'
import { DrawerCart } from '@/components/DrawerCart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <ProvidersComponent>
            <DrawerCart/>
            <NavbarComponent/>
            {children}  
          </ProvidersComponent>
        </body>
      </html>
    )
  }
